#**AIIE 2025 Python Review**
  **Dr. Christelle Scharff | Dr. Kaleema**

We have used built-in Python libraries.

    As python is opensource there are many libraries available that people have shared on ‘PyPi’, you can use ‘pip install’ to
    install theses packages.

    When you install Python from Python.org or Anaconda you also install pip, pip is a simple way to download packages at
    command line from PyPi repository.

     
    A module can contain any Python code we like.
    
    Programs are designed to be run, whereas modules are designed to be imported and used by programs.
    
    Syntax : import importable

    In the above syntax ‘importable’ can be a module such as collections, or it can be a Package or a module in a package.
    
    Example: Import os.path

    Pandas is an open-source library that provides high performance easy to use data analysis and data manipulation tool.
    
    It is built on top of NumPy.
    
    Pandas has built-in visualization features.
    
    Pandas can work with data from a wide variety of sources.

    To install pandas:
    
    conda install pandas
    
    or
    
    pip install pandas.


    [pandas] is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time
    periods for the same individuals. — Wikipedia

#Pandas
https://pandas.pydata.org/

##Pandas as series

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
list1 = [100,200,300,400,500,600,700]

In [ ]:
print(list1)

[100, 200, 300, 400, 500, 600, 700]

In [ ]:
ser1 = pd.Series(list1)

In [ ]:
ser1

0    100
1    200
2    300
3    400
4    500
5    600
6    700
dtype: int64

In [ ]:
ser1.values

array([100, 200, 300, 400, 500, 600, 700])

In [ ]:
ser1.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
ser1[0:7:2]

0    100
2    300
4    500
6    700
dtype: int64

In [ ]:
ser2 = pd.Series([800, 900])

In [ ]:
ser3 = ser1+ser2

In [ ]:
ser1

0    100
1    200
2    300
3    400
4    500
5    600
6    700
dtype: int64

In [ ]:
ser2

0    800
1    900
dtype: int64

In [ ]:
ser3

0     900.0
1    1100.0
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
dtype: float64

In [ ]:
#Constructing a series
series1 = pd.Series([0.25,0.55,0.65,1.25,6.58,4.30,8.9], index=['a','b','c','d','e','f','g'])

In [ ]:
series1

a    0.25
b    0.55
c    0.65
d    1.25
e    6.58
f    4.30
g    8.90
dtype: float64

In [ ]:
list1 =[1,2,3,4,6,7]
list1[2]

3

In [ ]:
#constructing a series from list
series2 = pd.Series(list1)
series2

0    1
1    2
2    3
3    4
4    6
5    7
dtype: int64

In [ ]:
#Series with explicit index
list2 =[0.25, 0.5, 0.75, 1.0]
ser2 = pd.Series(list2, index=['a','b','c','d'])
ser2

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
ser2.values #To get values from a series

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
ser2.index #to get index from a series

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
series3 = series1+series2
series3

0     1.25
1     2.55
2     3.65
3     5.25
4    12.58
5    11.30
6      NaN
dtype: float64

In [ ]:
series3[0] #extracting the values based on index

1.25

#### Series as specialized dictionary

In [ ]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}
population_dict

{'California': 38332521,
 'Florida': 19552860,
 'Illinois': 12882135,
 'New York': 19651127,
 'Texas': 26448193}

In [ ]:
population_newser = pd.Series(population_dict)
population_newser

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
#To access the series
#population['Texas']

In [ ]:
population_newser.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
population_newser.values

array([38332521, 26448193, 19651127, 19552860, 12882135])

In [ ]:
population_newser['New York']

19651127

## Pandas as DataFrame

#### Data Frame Construction

In [ ]:
from numpy.random import randn

In [ ]:
np.random.seed(101)

In [ ]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['I','II','III','IV'])

In [ ]:
df

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#Extract values by column
df['I']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: I, dtype: float64

In [ ]:
#Extract Values by rows
df[['I','II']]

          I        II
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [ ]:
#Adding new column to the data frame
df['New_column'] = df['I']+df['II']

In [ ]:
df

          I        II       III        IV  New_column
A  2.706850  0.628133  0.907969  0.503826    3.334983
B  0.651118 -0.319318 -0.848077  0.605965    0.331800
C -2.018168  0.740122  0.528813 -0.589001   -1.278046
D  0.188695 -0.758872 -0.933237  0.955057   -0.570177
E  0.190794  1.978757  2.605967  0.683509    2.169552

In [ ]:
#Drop the column temporarily
df.drop('New_column', axis =1)

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df

          I        II       III        IV  New_column
A  2.706850  0.628133  0.907969  0.503826    3.334983
B  0.651118 -0.319318 -0.848077  0.605965    0.331800
C -2.018168  0.740122  0.528813 -0.589001   -1.278046
D  0.188695 -0.758872 -0.933237  0.955057   -0.570177
E  0.190794  1.978757  2.605967  0.683509    2.169552

In [ ]:
#Drop the column permanently
df.drop('New_column', axis =1, inplace=True)

In [ ]:
df

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#Drop the row
df.drop('C', axis=0)

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#Drop the row permanently
df.drop('E', axis=0, inplace=True)

In [ ]:
df

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
#To get the row 'A' data based on row description
df.loc['A']

I      2.706850
II     0.628133
III    0.907969
IV     0.503826
Name: A, dtype: float64

In [ ]:
#To get the row 'A','B','C' data based on row description
df.loc[['A','B','C']]

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [ ]:
#To get the row 'A' data based on row index
df.iloc[0]

I      2.706850
II     0.628133
III    0.907969
IV     0.503826
Name: A, dtype: float64

In [ ]:
#To get all the rows data based on row index
df.iloc[2:]

          I        II       III        IV
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
df

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
#To extract the data at a particular index of row and column
df.loc['A','II']

0.6281327087844596

In [ ]:
df.iloc[0,1]

0.6281327087844596

In [ ]:
#To get the subset of the data
df.loc[['A','C'],['I','IV']]

          I        IV
A  2.706850  0.503826
C -2.018168 -0.589001

### Constructing a Data Frame from Series object

In [ ]:
population_dict = {'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}
population_series = pd.Series(population_dict)
population_series

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
population_df = pd.DataFrame(population_series, )
population_df

                   0
California  38332521
Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135

In [ ]:
population_dict = {'California': 38332521,'Texas': 26448193,'New York': 19651127,'Florida': 19552860,'Illinois': 12882135}

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}

In [ ]:
states = pd.DataFrame({'population': population_dict,'area': area_dict})
states

NameError: ignored

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
states.columns

Index(['population', 'area'], dtype='object')

### Conditional Selection

In [ ]:
#if you want to know where are values in the daataframe which are >0, it will give the result in boolean


df[df > 0 ]

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['I'] >0]

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#Get the resultant values of the data frame whose column 'I' >0
df[df['I'] >0]

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
# To get only column 'I'
df[df['I'] >0]['I']

A    2.706850
B    0.651118
D    0.188695
Name: I, dtype: float64

In [ ]:
df[(df['I']>0) & (df['IV']>0)]

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
df[(df['I']>0) | (df['IV']>1)]

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

### Index

#### Reset Index

In [ ]:
df

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.reset_index()

  index         I        II       III        IV
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

#### Set Index

In [ ]:
newindex = ['NY','NJ','CA','FL']
newindex

['NY', 'NJ', 'CA', 'FL']

In [ ]:
df['States'] =newindex
df

          I        II       III        IV States
A  2.706850  0.628133  0.907969  0.503826     NY
B  0.651118 -0.319318 -0.848077  0.605965     NJ
C -2.018168  0.740122  0.528813 -0.589001     CA
D  0.188695 -0.758872 -0.933237  0.955057     FL

In [ ]:
df.set_index('States')

               I        II       III        IV
States
NY      2.706850  0.628133  0.907969  0.503826
NJ      0.651118 -0.319318 -0.848077  0.605965
CA     -2.018168  0.740122  0.528813 -0.589001
FL      0.188695 -0.758872 -0.933237  0.955057

#### Multi-Index / Hierarchical Index

In [ ]:
outside_ind =['L1','L1','L1','L2','L2','L2']
inside_ind = [1,2,3,1,2,3]
hier_ind = list(zip(outside_ind, inside_ind))
hier_ind = pd.MultiIndex.from_tuples(hier_ind)

In [ ]:
df = pd.DataFrame(randn(6,2), hier_ind, ['A','B'])
df

             A         B
L1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
L2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [ ]:
df.index.names =['Level','Number']

In [ ]:
df

                     A         B
Level Number
L1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
L2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [ ]:
# To extract the data

df.loc['L1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [ ]:
df.xs('L1')

               A         B
Number
1       0.302665  1.693723
2      -1.706086 -1.159119
3      -0.134841  0.390528

In [ ]:
df.xs(1,level='Number' )

              A         B
Level
L1     0.302665  1.693723
L2     0.166905  0.184502

#### Hierarchical Indexing Example : 2

In [ ]:
index = [('California', 2000), ('California', 2010),('California', 2020),
('New York', 2000), ('New York', 2010),('New York', 2020),
('Texas', 2000), ('Texas', 2010), ('Texas', 2020)]

In [ ]:
populations = [33871648, 37253956,37250000,
18976457, 19378102,19378000,
20851820, 25145561, 25145000]

In [ ]:
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(California, 2020)    37250000
(New York, 2000)      18976457
(New York, 2010)      19378102
(New York, 2020)      19378000
(Texas, 2000)         20851820
(Texas, 2010)         25145561
(Texas, 2020)         25145000
dtype: int64

In [ ]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            ('California', 2020),
            (  'New York', 2000),
            (  'New York', 2010),
            (  'New York', 2020),
            (     'Texas', 2000),
            (     'Texas', 2010),
            (     'Texas', 2020)],
           )

In [ ]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
            2020    37250000
New York    2000    18976457
            2010    19378102
            2020    19378000
Texas       2000    20851820
            2010    25145561
            2020    25145000
dtype: int64

In [ ]:
unstacked_pop = pop.unstack()
unstacked_pop

                2000      2010      2020
California  33871648  37253956  37250000
New York    18976457  19378102  19378000
Texas       20851820  25145561  25145000

In [ ]:
unstacked_pop.stack()

California  2000    33871648
            2010    37253956
            2020    37250000
New York    2000    18976457
            2010    19378102
            2020    19378000
Texas       2000    20851820
            2010    25145561
            2020    25145000
dtype: int64

## Missing Data

#### With Numpy

In [ ]:
import numpy as np

vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [ ]:
1 + np.nan

nan

In [ ]:
0 * np.nan

nan

In [ ]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [ ]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

#### With Pandas

In [ ]:
#Constructing a DataFrame
data = pd.DataFrame([[1, np.nan, 2],[2, 3, 5],[np.nan, np.nan, 6], [5, np.nan, 6]])
data

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  NaN  6
3  5.0  NaN  6

In [ ]:
#dropna() to drop entire row if anyone one value in the row is NaN

data.dropna(axis=0, how='all')

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  NaN  6
3  5.0  NaN  6

In [ ]:
data.dropna(thresh=2)

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
3  5.0  NaN  6

In [ ]:
#dropna() to drop entire column if anyone one value in the row is NaN

df.dropna(axis=1, how='any')

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#dropna() to drop entire row if all the values in the row are NaN

df.dropna(axis = 0, how='all')

          I        II       III        IV
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#dropna() to drop entire column if all the values in the column are NaN
df.dropna(axis = 1, how='all')

                     A         B
Level Number
L1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
L2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [ ]:
#dropna() to drop entire column if any of the values in the column are NaN
df.dropna(axis='columns')

                     A         B
Level Number
L1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
L2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [ ]:
#dropna() with thersold =2 value, if there are two or more then it will drop the row/column
df.dropna(thresh=2)

                     A         B
Level Number
L1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
L2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [ ]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [ ]:
data.fillna(100)

       0      1  2
0    1.0  100.0  2
1    2.0    3.0  5
2  100.0  100.0  6
3    5.0  100.0  6

In [ ]:
# forward-fill
data.fillna(method='ffill')

<ipython-input-61-c47b1cefb12a>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  2.0  3.0  6
3  5.0  3.0  6

In [ ]:
# back-fill
data.fillna(method='bfill')

<ipython-input-62-7b95ada8f1ff>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')

     0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  5.0  NaN  6
3  5.0  NaN  6

In [ ]:
# fill-value
data.fillna(value='N/A')

a      1
b    N/A
c      2
d    N/A
e      3
dtype: object

In [ ]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [ ]:
data = pd.DataFrame([[1, np.nan, 2],[2, 3, 5],[np.nan, np.nan, 6], [5, np.nan, 6]])
data

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  NaN  6
3  5.0  NaN  6

In [ ]:
data.fillna(value=data.mean())

          0    1  2
0  1.000000  3.0  2
1  2.000000  3.0  5
2  2.666667  3.0  6
3  5.000000  3.0  6

### Groupby

In [ ]:
data = {'Department':['Sales','Finanace','Finanace','HR','HR','Marketing','IT','IT'],
        'Employess':['Sam','Alexia','Krish','Amy','Frank','Charles','Christlle','Ben'],
        'Salary(in Thousands)':[200,350,1850,450,560,800,950,850]}

In [ ]:
df = pd.DataFrame(data)
df

  Department  Employess  Salary(in Thousands)
0      Sales        Sam                   200
1   Finanace     Alexia                   350
2   Finanace      Krish                  1850
3         HR        Amy                   450
4         HR      Frank                   560
5  Marketing    Charles                   800
6         IT  Christlle                   950
7         IT        Ben                   850

In [ ]:
dept = df.groupby('Department')
dept

In [ ]:
dept = df.groupby('Department').describe()
dept

           Salary(in Thousands)                                             \
                          count    mean          std    min    25%     50%
Department
Finanace                    2.0  1100.0  1060.660172  350.0  725.0  1100.0
HR                          2.0   505.0    77.781746  450.0  477.5   505.0
IT                          2.0   900.0    70.710678  850.0  875.0   900.0
Marketing                   1.0   800.0          NaN  800.0  800.0   800.0
Sales                       1.0   200.0          NaN  200.0  200.0   200.0


               75%     max
Department
Finanace    1475.0  1850.0
HR           532.5   560.0
IT           925.0   950.0
Marketing    800.0   800.0
Sales        200.0   200.0

In [ ]:
dept = df.groupby('Department').describe()
dept

           Salary(in Thousands)                                             \
                          count    mean          std    min    25%     50%
Department
Finanace                    2.0  1100.0  1060.660172  350.0  725.0  1100.0
HR                          2.0   505.0    77.781746  450.0  477.5   505.0
IT                          2.0   900.0    70.710678  850.0  875.0   900.0
Marketing                   1.0   800.0          NaN  800.0  800.0   800.0
Sales                       1.0   200.0          NaN  200.0  200.0   200.0


               75%     max
Department
Finanace    1475.0  1850.0
HR           532.5   560.0
IT           925.0   950.0
Marketing    800.0   800.0
Sales        200.0   200.0

#Combining Datasets: Concat and Append

In [ ]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=['a','b','c'])
df1 = pd.DataFrame(ser1)
df2 = pd.DataFrame(ser2)

In [ ]:
df1

   0
1  A
2  B
3  C

In [ ]:
df2

   0
a  D
b  E
c  F

In [ ]:
pd.concat([df1, df2])

   0
1  A
2  B
3  C
a  D
b  E
c  F

In [ ]:
pd.concat([df1, df2], axis=1)

     0    0
1    A  NaN
2    B  NaN
3    C  NaN
a  NaN    D
b  NaN    E
c  NaN    F

In [ ]:
df1.append(df2)

   0
1  A
2  B
3  C
a  D
b  E
c  F

In [ ]:
def make_df(cols, ind):
 data = {c: [str(c) + str(i) for i in ind] for c in cols}
 return pd.DataFrame(data, ind)

In [ ]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1); print(df2);
print(pd.concat([df1, df2]));
print(pd.concat([df1, df2], axis =1));

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
     A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

In [ ]:
print(pd.concat([df1, df2], axis =1, ignore_index=True));

     0    1    2    3
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

In [ ]:
print(pd.concat([df1, df2], keys=['x', 'y']));

      A   B
x 1  A1  B1
  2  A2  B2
y 3  A3  B3
  4  A4  B4

In [ ]:
print(pd.concat([df1, df2], join='inner'));

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [ ]:
print(df1.append(df2))

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

# Combining Datasets: Merge and Join

One-to-one joins

In [ ]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],'hire_date': [2004, 2008, 2012, 2014]})

In [ ]:
#df5 = pd.concat(df1,df2)

In [ ]:
df3 = pd.merge(df1, df2, on='employee')
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

Many-to-one joins

In [ ]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],'supervisor': ['Carly', 'Guido', 'Steve']})

In [ ]:
df5 = pd.merge(df3, df4)
df5

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

Many-to-many joins

In [ ]:
df6 = pd.DataFrame({'group': ['Accounting', 'Accounting',
'Engineering', 'Engineering', 'HR', 'HR'],'skills': ['math', 'spreadsheets', 'coding', 'linux',
'spreadsheets', 'organization']})

In [ ]:
print(pd.merge(df1, df6))

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

Specification of the Merge Key

In [ ]:
print(pd.merge(df1, df2, on='employee'))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [ ]:
print(pd.merge(df1, df3, left_on="employee", right_on="group"))

Empty DataFrame
Columns: [employee_x, group_x, employee_y, group_y, hire_date]
Index: []

In [ ]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [ ]:
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

### Operations on Data Frames

In [ ]:
df = pd.read_csv('example')
df

In [ ]:
df.to_csv('example',index=False)

In [ ]:
df['col2'].unique()

In [ ]:
df['col2'].nunique()

In [ ]:
df['col2'].value_counts()

## Pivot Tables

In [ ]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [ ]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [ ]:
df = pd.read_csv('/content/titanic-train.csv')

In [ ]:
df.head(10)

In [ ]:
df.pivot_table(index='total_bedrooms',
               columns='median_income',
               values='median_house_value',
               aggfunc='min')

## Correlations
In Pandas you can also calculate corelations between features. Which will help to find redudant information.

In [ ]:
df['IsFemale'] = df['Sex'] == 'female'

In [ ]:
df.plot()

In [ ]:
correlated_with_survived = df.corr()['Survived'].sort_values()
correlated_with_survived

## The Pandas Index Object

In [ ]:
ind = pd.Index([[[2, 3, 7],[7, 5, 11]],[[8,6,5],[9,4,3]]])
ind

In [ ]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

In [ ]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [ ]:
indA & indB # intersection

In [ ]:
indA | indB # union

In [ ]:
indA ^ indB # symmetric difference

In [ ]:
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

In [ ]:
data['density'] = data['pop'] / data['area']
data

In [ ]:
data.T

In [ ]:
data.iloc[:3, :2]

In [ ]:
data.loc[:'Illinois', :'pop']

In [ ]:
#data.ix[:3, :'pop']

### Data Indexing and Selection

#### Data Selection in Series

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
data

In [ ]:
'0.25' in data

In [ ]:
data.keys()

In [ ]:
data['e'] = 1.25

In [ ]:
data.keys()

In [ ]:
data.values

In [ ]:
# slicing by explicit index
data['a':'c']

In [ ]:
# slicing by implicit integer index
data[0:2]

In [ ]:
# masking
data[(data > 0.3) & (data < 0.8)]

### Operating on Data in Pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 100, 8))
ser

In [ ]:
np.exp(ser)

In [ ]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
columns=['A', 'B', 'C', 'D'])
df

In [ ]:
np.sin(df * np.pi / 4)

### Dataframe from a CSV File

In [ ]:
# from sklearn.datasets import fetch_california_housing
# HousingDF = fetch_california_housing()

In [ ]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/Titanic Dataset.csv')

In [13]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [14]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [15]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [16]:
df.shape

(891, 12)

In [19]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Gender          object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [21]:
df[df.notnull()]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [22]:
df.notnull()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,True,True,True,True,True,True,True,True,True,True,False,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,True,True,True,True,True,True,True,True,True,False,True
887,True,True,True,True,True,True,True,True,True,True,True,True
888,True,True,True,True,True,False,True,True,True,True,False,True
889,True,True,True,True,True,True,True,True,True,True,True,True
890,True,True,True,True,True,True,True,True,True,True,False,True

In [23]:
print(df.isnull().values.any()) #To check if there any missing values

True

In [24]:
print(df.isnull().sum().sum()) #To know how many null values

866

In [25]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [30]:
df1 = df.copy()
df1.dropna()
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [35]:
df1.iloc[:,:]
display(df1.dropna())

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C